version: "3.9"

services:
  main_db:
    container_name: irrigate_db
    image: mongo:latest
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
      MONGO_INITDB_DATABASE: mongodb
      MONGODB_DATA_DIR: /data/db/main
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - ./data/main:/data/db
    ports:
      - 27017:27017
    networks:
      - main_db

  api:
    container_name: irrigate_api
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - main_db
    volumes:
      - ./:/app/api/
    networks:
      - main_db

networks:
  main_db:
    driver: bridge
